'use client';
import Image from 'next/image';
import Link from 'next/link';
import {ArrowLeft, ArrowRight, ChevronDown, Heart, Menu, Search, ShoppingBag, UserRound} from 'lucide-react';
import {products,money} from '../lib/products';
import {useStore} from '../lib/store';
import menswearImage from '../lib/kente panel blazers.jpg';
import shoesImage from '../lib/olowo leather derby.jpg';
import accessoriesImage from '../lib/landing page.jpg';
import motionImage from '../lib/motion.jpeg';
const BRAND='DAMMY T & MOTION WEARS';

export default function Home(){const [category,setCategory]=React.useState('All');const [query,setQuery]=React.useState('');const [splashVisible,setSplashVisible]=React.useState(true); React.useEffect(()=>{const timeout=window.setTimeout(()=>setSplashVisible(false),1800); return()=>window.clearTimeout(timeout)},[]); const {cart,wishlist,toggleWishlist,setCartOpen}=useStore(); const shown=products.filter(p=>(category==='All'||p.category===category)&&p.name.toLowerCase().includes(query.toLowerCase())); return <main>
{splashVisible&&<div id="brand" className="splash-screen" role="status" aria-label="Dammy T and Motion Wears"><div className="splash-mark"><span className="splash-kicker">Clothing · Accessories</span><strong>Dammy T</strong><span className="splash-and">&amp;</span><strong>Motion Wears</strong></div></div>}
<header className="border-b border-[var(--line)] bg-[var(--paper)]"><div className="mx-auto flex max-w-[1400px] items-center justify-between px-5 py-5 lg:px-10"><button className="lg:hidden"><Menu size={21}/></button><Link href="/" className="display text-2xl font-semibold tracking-[.18em]">MIONDO</Link><nav className="hidden items-center gap-8 text-[11px] font-semibold uppercase tracking-[.16em] lg:flex"><a href="#brand">Dammy T</a><a href="#shop">New in</a><a href="#shop">Women</a><a href="#shop">Men</a><a href="#shop">Shoes</a><a href="#story">The journal</a></nav><div className="flex items-center gap-4"><button aria-label="Search"><Search size={19}/></button><button aria-label="Account"><UserRound size={19}/></button><button aria-label="Wishlist" className="relative"><Heart size={19}/>{wishlist.length>0&&<span className="absolute -right-2 -top-2 text-[9px]">{wishlist.length}</span>}</button><button aria-label="Cart" className="relative" onClick={()=>setCartOpen(true)}><ShoppingBag size={19}/><span className="absolute -right-2 -top-2 bg-[var(--accent)] px-1 text-[9px] text-white">{cart.reduce((a,i)=>a+i.quantity,0)}</span></button></div></div></header>
<HeroCarousel/>
<section id="shop" className="mx-auto max-w-[1400px] px-5 py-16 lg:px-10"><div className="mb-10 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="mb-3 text-[10px] font-bold uppercase tracking-[.2em] text-[var(--accent)]">The marketplace</p><h2 className="display text-4xl">Find your next favourite.</h2></div><div className="flex items-center gap-5 border-b border-[var(--ink)] pb-2"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search pieces" className="w-44 bg-transparent text-sm outline-none placeholder:text-[#888]"/></div></div><div className="mb-8 flex items-center justify-between border-y border-[var(--line)] py-4"><div className="hide-scrollbar flex gap-7 overflow-auto">{['All','Women','Men','Shoes'].map(item=><button key={item} onClick={()=>setCategory(item)} className={`whitespace-nowrap text-[11px] font-bold uppercase tracking-[.15em] ${category===item?'text-[var(--accent)]':'text-[#777]'}`}>{item}</button>)}</div><button className="hidden items-center gap-2 text-[11px] font-bold uppercase tracking-[.15em] sm:flex">Sort: Featured <ChevronDown size={14}/></button></div><div className="grid grid-cols-2 gap-x-3 gap-y-10 md:grid-cols-3 lg:grid-cols-4 lg:gap-x-5">{shown.map(product=><article key={product.id} className="group"><div className="relative aspect-[.78] overflow-hidden bg-[#e7e3dc]"><Image src={product.image} alt={product.name} fill className="object-cover transition duration-700 group-hover:scale-105" sizes="(max-width: 768px) 50vw, 25vw"/><button aria-label={`Wishlist ${product.name}`} onClick={()=>toggleWishlist(product.id)} className="absolute right-3 top-3 bg-[var(--paper)] p-2"><Heart size={16} fill={wishlist.includes(product.id)?'currentColor':'none'} className={wishlist.includes(product.id)?'text-[var(--accent)]':''}/></button>{product.badge&&<span className="absolute left-3 top-3 bg-white px-2 py-1 text-[9px] font-bold uppercase tracking-widest">{product.badge}</span>}</div><div className="pt-4"><div className="flex justify-between gap-2"><div><h3 className="text-sm font-semibold">{product.name}</h3><p className="mt-1 text-xs text-[#777]">{product.seller}</p></div><p className="text-sm font-semibold">{money(product.price)}</p></div><p className="mt-3 text-[10px] uppercase tracking-wider text-[#888]">{product.color} · {product.rating} ★</p></div></article>)}</div>{shown.length===0&&<p className="py-20 text-center text-sm text-[#777]">No pieces match that search.</p>}</section>
<section id="story" className="border-y border-[var(--line)] bg-[#e8e1d6] px-5 py-20 lg:px-10"><div className="mx-auto grid max-w-[1400px] gap-10 md:grid-cols-2 md:items-center"><div><p className="mb-4 text-[10px] font-bold uppercase tracking-[.2em] text-[var(--accent)]">Our point of view</p><h2 className="display max-w-md text-4xl leading-tight md:text-5xl">Style is a language. Speak in your own accent.</h2><p className="mt-5 max-w-md text-sm leading-6 text-[#59554d]">Dammy T brings independent African designers and discerning wardrobes together. Discover the makers behind the pieces and buy with confidence.</p><a href="#shop" className="mt-8 inline-flex items-center gap-2 text-[11px] font-bold uppercase tracking-[.16em] underline underline-offset-8">Meet the makers <ArrowRight size={15}/></a></div><div className="relative aspect-[1.3] overflow-hidden"><Image src={motionImage} alt="Dammy T and Motion Wears fashion" fill className="object-cover"/></div></div></section>
<footer className="bg-[var(--ink)] px-5 py-12 text-white lg:px-10"><div className="mx-auto flex max-w-[1400px] flex-col justify-between gap-8 md:flex-row"><div><Link href="/" className="display text-2xl tracking-[.18em]">MIONDO</Link><p className="mt-3 max-w-xs text-xs leading-5 text-white/50">Modern African fashion, delivered across Nigeria and beyond.</p></div><div className="flex gap-12 text-[10px] font-bold uppercase tracking-[.15em] text-white/70"><a href="#shop">Shop</a><a href="#story">About</a><a href="#brand">Dammy T &amp; Motion Wears</a><a href="#">Help</a></div></div></footer><CartDrawer/></main>}
function HeroCarousel(){const slides=[{image:menswearImage,eyebrow:'Classic menswear',title:'Tailoring with presence.',description:'Sharp silhouettes, rich texture and considered details for every entrance.'},{image:shoesImage,eyebrow:'Shoes',title:'Walk your own line.',description:'Polished leather and lasting construction, made to move with you.'},{image:accessoriesImage,eyebrow:'Bags & accessories',title:'Carry the distinction.',description:'Finishing pieces that bring character to the everyday.'}]; const [active,setActive]=React.useState(0); React.useEffect(()=>{const timer=window.setInterval(()=>setActive(current=>(current+1)%slides.length),6000); return()=>window.clearInterval(timer)},[slides.length]); const slide=slides[active]; const changeSlide=(direction:number)=>setActive((active+direction+slides.length)%slides.length); return <section className="relative min-h-[580px] overflow-hidden bg-[#292a25] text-white" aria-roledescription="carousel" aria-label="Featured menswear, shoes and accessories"><div className="absolute inset-0"><Image src={slide.image} alt={slide.eyebrow} fill priority={active===0} className="object-cover object-center transition-opacity duration-700" sizes="100vw"/><div className="absolute inset-0 bg-black/40"/></div><div className="relative mx-auto flex min-h-[580px] max-w-[1400px] items-end justify-between gap-8 px-5 pb-12 lg:px-10 lg:pb-20"><div className="max-w-xl"><p className="mb-5 text-[11px] uppercase tracking-[.25em] text-[#e7b79d]">{slide.eyebrow}</p><h1 className="display text-5xl leading-[.95] md:text-7xl">{slide.title}</h1><p className="mt-6 max-w-sm text-sm leading-6 text-white/80">{slide.description}</p><a href="#shop" className="mt-8 inline-flex items-center gap-3 border border-white px-5 py-3 text-[11px] font-bold uppercase tracking-[.16em] transition hover:bg-white hover:text-black">Explore the edit <ArrowRight size={16}/></a></div><div className="flex shrink-0 items-center gap-4"><button type="button" aria-label="Previous slide" onClick={()=>changeSlide(-1)} className="border border-white/60 p-3 transition hover:bg-white hover:text-black"><ArrowLeft size={17}/></button><div className="flex gap-2" role="tablist" aria-label="Featured categories">{slides.map((item,index)=><button type="button" key={item.eyebrow} role="tab" aria-selected={active===index} aria-label={`Show ${item.eyebrow}`} onClick={()=>setActive(index)} className={`h-1 w-8 ${active===index?'bg-white':'bg-white/40'}`}/>)}</div><button type="button" aria-label="Next slide" onClick={()=>changeSlide(1)} className="border border-white/60 p-3 transition hover:bg-white hover:text-black"><ArrowRight size={17}/></button></div></div></section>}
function CartDrawer(){const {cart,cartOpen,setCartOpen,removeFromCart}=useStore(); const total=cart.reduce((sum,item)=>sum+item.price*item.quantity,0); return cartOpen?<div className="fixed inset-0 z-50 bg-black/30" onClick={()=>setCartOpen(false)}><aside onClick={e=>e.stopPropagation()} className="absolute right-0 top-0 flex h-full w-full max-w-md flex-col bg-[var(--paper)] p-6"><div className="flex justify-between border-b border-[var(--line)] pb-5"><h2 className="display text-2xl">Your bag</h2><button onClick={()=>setCartOpen(false)} className="text-2xl">×</button></div><div className="flex-1 py-6">{cart.length===0?<p className="py-20 text-center text-sm text-[#777]">Your bag is waiting for something special.</p>:cart.map(item=><div key={`${item.id}-${item.size}`} className="mb-5 flex gap-4"><div className="relative h-24 w-20"><Image src={item.image} alt={item.name} fill className="object-cover"/></div><div className="flex-1"><p className="text-sm font-semibold">{item.name}</p><p className="mt-1 text-xs text-[#777]">Size {item.size} · Qty {item.quantity}</p><p className="mt-3 text-sm">{money(item.price*item.quantity)}</p></div><button onClick={()=>removeFromCart(item.id)} className="text-xs text-[#888]">Remove</button></div>)}</div><div className="border-t border-[var(--line)] pt-5"><div className="mb-5 flex justify-between text-sm"><span>Total</span><strong>{money(total)}</strong></div><Link href="/checkout" className={`block bg-[var(--ink)] py-4 text-center text-[11px] font-bold uppercase tracking-[.16em] text-white ${cart.length===0?'pointer-events-none opacity-40':''}`}>Checkout securely</Link></div></aside></div>:null}
import React from 'react';
