'use client';
import React,{useEffect,useState} from 'react';
import Image from 'next/image';
import Link from 'next/link';
import {ArrowRight,ChevronDown,Heart,Menu,Minus,Plus,Search,ShoppingBag,UserRound,X} from 'lucide-react';
import {products,money,Product} from '../lib/products';
import {useStore} from '../lib/store';
import menswearImage from '../lib/kente panel blazers.jpg';
import shoesImage from '../lib/olowo leather derby.jpg';
import accessoriesImage from '../lib/landing page.jpg';
import motionImage from '../lib/motion.jpeg';

export default function Home(){
  const [category,setCategory]=useState('All');const [query,setQuery]=useState('');const [splashVisible,setSplashVisible]=useState(true);
  const {cart,wishlist,toggleWishlist,setCartOpen}=useStore();
  useEffect(()=>{const timeout=window.setTimeout(()=>setSplashVisible(false),1800);const initial=new URLSearchParams(window.location.search).get('category');if(initial&&['Women','Men','Shoes'].includes(initial))setCategory(initial);return()=>window.clearTimeout(timeout)},[]);
  const shown=products.filter(product=>(category==='All'||product.category===category)&&(product.name.toLowerCase().includes(query.toLowerCase())||product.seller.toLowerCase().includes(query.toLowerCase())));
  return <main>{splashVisible&&<div id="brand" className="splash-screen" role="status" aria-label="Dammy T and Motion Wears"><div className="splash-mark"><span className="splash-kicker">Clothing · Accessories</span><strong>Dammy T</strong><span className="splash-and">&amp;</span><strong>Motion Wears</strong></div></div>}
    <header className="border-b border-[var(--line)] bg-[var(--paper)]"><div className="mx-auto flex max-w-[1400px] items-center justify-between px-5 py-5 lg:px-10"><Link href="/menu" className="lg:hidden" aria-label="Open menu"><Menu size={21}/></Link><Link href="/" className="text-sm font-semibold uppercase tracking-[.12em]">DAMMY T &amp; MOTION WEARS</Link><nav className="hidden items-center gap-8 text-[11px] font-semibold uppercase tracking-[.16em] lg:flex"><a href="#brand">Dammy T</a><a href="#shop">New in</a><a href="#shop" onClick={()=>setCategory('Women')}>Women</a><a href="#shop" onClick={()=>setCategory('Men')}>Men</a><a href="#shop" onClick={()=>setCategory('Shoes')}>Shoes</a><a href="#story">The journal</a></nav><div className="flex items-center gap-4"><Link href="/search" aria-label="Search"><Search size={19}/></Link><Link href="/account" aria-label="Account"><UserRound size={19}/></Link><button aria-label="Wishlist" className="relative" onClick={()=>setCartOpen(true)}><Heart size={19}/>{wishlist.length>0&&<span className="absolute -right-2 -top-2 text-[9px]">{wishlist.length}</span>}</button><button aria-label="Cart" className="relative" onClick={()=>setCartOpen(true)}><ShoppingBag size={19}/><span className="absolute -right-2 -top-2 bg-[var(--accent)] px-1 text-[9px] text-white">{cart.reduce((total,item)=>total+item.quantity,0)}</span></button></div></div></header>
    <HeroCarousel/>
    <section id="shop" className="mx-auto max-w-[1400px] px-5 py-16 lg:px-10"><div className="mb-10 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="mb-3 text-[10px] font-bold uppercase tracking-[.2em] text-[var(--accent)]">The marketplace</p><h2 className="display text-4xl">Find your next favourite.</h2></div><label className="flex items-center gap-5 border-b border-[var(--ink)] pb-2"><Search size={16}/><span className="sr-only">Search products</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search pieces or designers" className="w-52 bg-transparent text-sm outline-none placeholder:text-[#888]"/></label></div><div className="mb-8 flex items-center justify-between border-y border-[var(--line)] py-4"><div className="hide-scrollbar flex gap-7 overflow-auto">{['All','Women','Men','Shoes'].map(item=><button key={item} onClick={()=>setCategory(item)} className={`whitespace-nowrap text-[11px] font-bold uppercase tracking-[.15em] ${category===item?'text-[var(--accent)]':'text-[#777]'}`}>{item}</button>)}</div><button className="hidden items-center gap-2 text-[11px] font-bold uppercase tracking-[.15em] sm:flex">Sort: Featured <ChevronDown size={14}/></button></div><div className="grid grid-cols-2 gap-x-3 gap-y-10 md:grid-cols-3 lg:grid-cols-4 lg:gap-x-5">{shown.map(product=><ProductCard key={product.id} product={product} wishlisted={wishlist.includes(product.id)} onWishlist={()=>toggleWishlist(product.id)}/>)}</div>{shown.length===0&&<p className="py-20 text-center text-sm text-[#777]">No products found. Try another search or category.</p>}</section>
    <section id="story" className="border-y border-[var(--line)] bg-[#e8e1d6] px-5 py-20 lg:px-10"><div className="mx-auto grid max-w-[1400px] gap-10 md:grid-cols-2 md:items-center"><div><p className="mb-4 text-[10px] font-bold uppercase tracking-[.2em] text-[var(--accent)]">Our point of view</p><h2 className="display max-w-md text-4xl leading-tight md:text-5xl">Style is a language. Speak in your own accent.</h2><p className="mt-5 max-w-md text-sm leading-6 text-[#59554d]">Dammy T brings independent African designers and discerning wardrobes together. Discover the makers behind the pieces and buy with confidence.</p><a href="#shop" className="mt-8 inline-flex items-center gap-2 text-[11px] font-bold uppercase tracking-[.16em] underline underline-offset-8">Meet the makers <ArrowRight size={15}/></a></div><div className="relative aspect-[3/4] overflow-hidden bg-[#dedbd2] md:aspect-[4/5]"><Image src={motionImage} alt="Dammy T and Motion Wears fashion" fill className="object-contain object-top"/></div></div></section>
    <footer className="bg-[var(--ink)] px-5 py-12 text-white lg:px-10"><div className="mx-auto flex max-w-[1400px] flex-col justify-between gap-8 md:flex-row"><div><Link href="/" className="text-sm font-semibold uppercase tracking-[.12em]">DAMMY T &amp; MOTION WEARS</Link><p className="mt-3 max-w-xs text-xs leading-5 text-white/50">Modern African fashion, delivered across Nigeria and beyond.</p></div><div className="flex gap-12 text-[10px] font-bold uppercase tracking-[.15em] text-white/70"><a href="#shop">Shop</a><a href="#story">About</a><Link href="/seller">Sell with us</Link><a href="mailto:help@dammytmotionwears.ng">Help</a></div></div></footer><CartDrawer/></main>
}
function ProductCard({product,wishlisted,onWishlist}:{product:Product;wishlisted:boolean;onWishlist:()=>void}){return <article className="group"><Link href={`/product/${product.id}`} className="block"><div className="relative aspect-[.78] overflow-hidden bg-[#e7e3dc]"><Image src={product.image} alt={product.name} fill className="object-cover transition duration-700 group-hover:scale-105" sizes="(max-width: 768px) 50vw, 25vw"/><span className="absolute left-3 top-3 bg-white px-2 py-1 text-[9px] font-bold uppercase tracking-widest">{product.badge||product.category}</span></div><div className="flex justify-between gap-2 pt-4"><div><h3 className="text-sm font-semibold">{product.name}</h3><p className="mt-1 text-xs text-[#777]">{product.seller}</p></div><p className="text-sm font-semibold">{money(product.price)}</p></div><p className="mt-3 text-[10px] uppercase tracking-wider text-[#888]">{product.color} · {product.rating} ★</p></Link><button aria-label={`${wishlisted?'Remove':'Add'} ${product.name} ${wishlisted?'from ': 'to '}wishlist`} onClick={onWishlist} className="mt-3 inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-widest text-[#777]"><Heart size={14} fill={wishlisted?'currentColor':'none'} className={wishlisted?'text-[var(--accent)]':''}/>{wishlisted?'Saved':'Save'}</button></article>}
function HeroCarousel(){const slides=[{image:menswearImage,eyebrow:'Classic menswear',title:'Tailoring with presence.',description:'Sharp silhouettes, rich texture and considered details for every entrance.'},{image:shoesImage,eyebrow:'Shoes',title:'Walk your own line.',description:'Polished leather and lasting construction, made to move with you.'},{image:accessoriesImage,eyebrow:'Bags & accessories',title:'Carry the distinction.',description:'Finishing pieces that bring character to the everyday.'}];const [active,setActive]=useState(0);useEffect(()=>{const timer=window.setInterval(()=>setActive(current=>(current+1)%slides.length),6000);return()=>window.clearInterval(timer)},[slides.length]);const slide=slides[active];return <section className="relative min-h-[580px] overflow-hidden bg-[#292a25] text-white" aria-roledescription="carousel" aria-label="Featured fashion"><div className="absolute inset-0"><Image src={slide.image} alt={slide.eyebrow} fill priority={active===0} className="object-contain object-top transition-opacity duration-700 md:left-auto md:right-0 md:w-[52%]" sizes="100vw"/><div className="absolute inset-0 bg-black/40"/></div><div className="relative mx-auto flex min-h-[580px] max-w-[1400px] items-end px-5 pb-12 lg:px-10 lg:pb-20"><div className="max-w-xl"><p className="mb-5 text-[11px] uppercase tracking-[.25em] text-[#e7b79d]">{slide.eyebrow}</p><h1 className="display text-5xl leading-[.95] md:text-7xl">{slide.title}</h1><p className="mt-6 max-w-sm text-sm leading-6 text-white/80">{slide.description}</p><a href="#shop" className="mt-8 inline-flex items-center gap-3 border border-white px-5 py-3 text-[11px] font-bold uppercase tracking-[.16em] transition hover:bg-white hover:text-black">Explore the edit <ArrowRight size={16}/></a></div></div></section>}
function CartDrawer(){const {cart,cartOpen,setCartOpen,removeFromCart,changeQuantity,notice,clearNotice}=useStore();const total=cart.reduce((sum,item)=>sum+item.price*item.quantity,0);useEffect(()=>{if(!notice)return;const timeout=window.setTimeout(clearNotice,2600);return()=>window.clearTimeout(timeout)},[notice,clearNotice]);return cartOpen?<div className="fixed inset-0 z-50 bg-black/30" onClick={()=>setCartOpen(false)}><aside onClick={event=>event.stopPropagation()} className="absolute right-0 top-0 flex h-full w-full max-w-md flex-col bg-[var(--paper)] p-6" aria-label="Shopping bag"><div className="flex justify-between border-b border-[var(--line)] pb-5"><h2 className="display text-2xl">Your bag</h2><button aria-label="Close bag" onClick={()=>setCartOpen(false)}><X size={20}/></button></div>{notice&&<p role="status" className="mt-4 bg-[#edf6eb] p-3 text-xs text-[#466342]">{notice}</p>}<div className="flex-1 overflow-y-auto py-6">{cart.length===0?<div className="py-20 text-center"><p className="text-sm text-[#777]">Your bag is waiting for something special.</p><Link href="#shop" onClick={()=>setCartOpen(false)} className="mt-5 inline-block text-[10px] font-bold uppercase tracking-widest underline">Continue shopping</Link></div>:cart.map(item=><div key={`${item.id}-${item.size}`} className="mb-6 flex gap-4"><div className="relative h-24 w-20 shrink-0"><Image src={item.image} alt={item.name} fill className="object-cover"/></div><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{item.name}</p><p className="mt-1 text-xs text-[#777]">Size {item.size} · {money(item.price)}</p><div className="mt-3 flex items-center gap-3"><button aria-label={`Decrease ${item.name} quantity`} onClick={()=>changeQuantity(item.id,item.size,-1)} className="border border-[var(--line)] p-1"><Minus size={13}/></button><span className="w-4 text-center text-sm">{item.quantity}</span><button aria-label={`Increase ${item.name} quantity`} onClick={()=>changeQuantity(item.id,item.size,1)} className="border border-[var(--line)] p-1"><Plus size={13}/></button></div></div><div className="flex flex-col items-end justify-between"><p className="text-sm font-semibold">{money(item.price*item.quantity)}</p><button onClick={()=>removeFromCart(item.id,item.size)} className="text-xs text-[#888] underline">Remove</button></div></div>)}</div><div className="border-t border-[var(--line)] pt-5"><div className="mb-5 flex justify-between text-sm"><span>Total</span><strong>{money(total)}</strong></div><Link href="/checkout" onClick={()=>setCartOpen(false)} className={`block bg-[var(--ink)] py-4 text-center text-[11px] font-bold uppercase tracking-[.16em] text-white ${cart.length===0?'pointer-events-none opacity-40':''}`}>Checkout securely</Link></div></aside></div>:null}
